version: '2'
services:
  web:
    image: baffedu/aproxy
    volumes: 
      - ./code/:/var/www/html/  
    networks: 
      baff:
      private:
    ports: 
      - 80:80
  php-fpm:
    image: baffedu/php-fpm
    volumes: 
      - ./code/:/var/www/html/
    networks: 
      baff:
      private:
        aliases: 
          - fpm-host
  crontab:
    image: baffedu/php-cli:devlop
    volumes: 
      - ./code/:/var/www/html/
      # 如果是正常情况下 下面这句不需要 这里覆盖了默认的计划任务
      - ./code/root:/var/spool/cron/crontabs/root

networks:
  baff:
    external: true
  private:
